/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_j360_jni_bridge_ImageBridge */

#ifndef _Included_me_j360_jni_bridge_ImageBridge
#define _Included_me_j360_jni_bridge_ImageBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_j360_jni_bridge_ImageBridge
 * Method:    filter
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_me_j360_jni_bridge_ImageBridge_filter
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
