/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_j360_jni_bridge_BridgeListener */

#ifndef _Included_me_j360_jni_bridge_BridgeListener
#define _Included_me_j360_jni_bridge_BridgeListener
#ifdef __cplusplus

class CommonListener {

public:

    JavaVM* jvm;//java虚拟机
    JNIEnv *jenv;//native线程env对象
    jobject jobj;//全局对象
    jmethodID jmid;//java 方法id,可以根据实际情况创建多个。

public:

    CommonListener(JavaVM* vm, JNIEnv *jenv, jobject obj);
    ~CommonListener();

    void onProgress(int type, int code, const char *msg);

};

extern "C" {
#endif



#ifdef __cplusplus
}
#endif
#endif
