/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_j360_jni_bridge_AsyncBridgeService */

#ifndef _Included_me_j360_jni_bridge_AsyncBridgeService
#define _Included_me_j360_jni_bridge_AsyncBridgeService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_j360_jni_bridge_AsyncBridgeService
 * Method:    call
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_j360_jni_bridge_AsyncBridgeService_call
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
