/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_j360_jni_bridge_ImageBridgeCallback */

#ifndef _Included_me_j360_jni_bridge_ImageBridgeCallback
#define _Included_me_j360_jni_bridge_ImageBridgeCallback
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_j360_jni_bridge_ImageBridgeCallback
 * Method:    getInstance
 * Signature: ()Lme/j360/jni/bridge/ImageBridgeCallback;
 */
JNIEXPORT jobject JNICALL Java_me_j360_jni_bridge_ImageBridgeCallback_getInstance
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
